trigger:
- main

parameters:
- name: locationStage1
  type: string
  default: './path/to/default/location1'
  displayName: 'Location for Stage 1'

- name: locationStage2
  type: string
  default: './path/to/default/location2'
  displayName: 'Location for Stage 2'

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - script: |
        echo "Using location: ${{ parameters.locationStage1 }}"
        # Add more steps that use this location
      displayName: 'Use Location for Stage 1, Job 1'

- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: Job2
    steps:
    - script: |
        echo "Using location: ${{ parameters.locationStage2 }}"
        # Add more steps that use this location
      displayName: 'Use Location for Stage 2, Job 2'
